# Generated by Django 4.2.2 on 2023-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_accion_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='ticker',
            field=models.CharField(max_length=4),
        ),
    ]
